### ISSUE TITLE
Source-code availability

### ISSUE THREAD

**Issue by nfp0** [scottywei/bioi-g60ble#1]
Hello there.
I was looking forward to buy this PCB, but I can't find where the firmware's source code is.
It says in the product page it's QMK, but I can't find it anywhere.

**Comment by oeywil** [comment]
Yeah, not to be found in the QMK repo or mentioned in any pull requests.

**Comment by scottywei** [comment]
@nfp0 @oeywil just issued a pull request to the qmk master repo

**Comment by nfp0** [comment]
@scottywei Can you link us to it? I've searched but I can't find it.

**Comment by ghost** [comment]
@nfp0 https://github.com/qmk/qmk_firmware/pull/9552

Thanks @scottywei!

**Comment by nfp0** [comment]
Oh, I thought the code would show up on this repository.
Awesome news! Now I can finally buy this PCB. Thanks @scottywei !

**Comment by latincompass** [comment]
> Oh, I thought the code would show up on this repository.
> Awesome news! Now I can finally buy this PCB. Thanks @scottywei !

yes,he is the god of the world,BLE is our final require
