### ISSUE TITLE
Enter layer 1 automatically in Bluetooth mode

### ISSUE THREAD

**Issue by ichiaohsu** [scottywei/bioi-g60ble#2]
## How to reproduce
When using in Bluetooth mode for a period of time, my BIOI keyboard will trigger layer 1 automatically. Once I connect a USB cord, then it's back to normal.

I do have a MO(1) in my layer 0. Pressing it will enter the layer 1, while releasing it will go back to layer 0. 

This issue only happens in bluetooth mode. I think my MO(1) function key is quite normal during a cable usage.

**Comment by scottywei** [comment]
Have you tried the latest firmware? In the old firmware, when you press the MO(1) key for a while in Bluetooth mode, it will lock the keyboard in layer 1. this problem has been fixed in the latest firmware

**Comment by ichiaohsu** [comment]
This issue happens after I upgrade to v1.2. Since it's a known issue, I will try to flash a v1.2 again.

**Comment by ichiaohsu** [comment]
It's fixed after upgraded to latest firmware. Thank you for the help!
