### ISSUE TITLE
Please share QMK code for 1.5 release

### ISSUE THREAD

**Issue by will-hedges** [scottywei/bioi-g60ble#20]
Hi Scotty, I am loving my G60BLE.

I'm looking at your previous documentation for the 1.4 and 1.5 releases, but since I made my own keymap, I can't get the reset and force bluetooth commands to work.

Would you please share the full keymap source code to us with all files? Or open a PR to QMK?

Thanks

**Comment by will-hedges** [comment]
Additionally, this would help for users having an issue with the PC not recognizing the G60BLE after restart

**Comment by scottywei** [comment]
Hi, Will
You can find the code for G60BLE in my fork of QMK firmware here:
https://github.com/scottywei/qmk_firmware/tree/update-and-add-bioi-keyboards/keyboards/bioi

I'm working on merging them to the QMK master repo, but there is a lot of
work to do, it might take a while.

and about your question, is that happened when you're using bluetooth mode?
if it is, it can be the problem of the driver of your bluetooth adapter,
you can try disallow the system to shutdown the adapter for power saving in
"Devices Manager" in Windows.
