### ISSUE TITLE
How is BT defined?

### ISSUE THREAD

**Issue by mrnoisytiger** [scottywei/bioi-g60ble#3]
Hi! 

I was looking at your QMK firmware for the G60BLE over https://github.com/qmk/qmk_firmware/blob/master/keyboards/bioi/g60ble/config.h and I'm a bit confused. Looks like you are using the MDBT40 chip, which normally hooks into _MISO/MOSI/SLK_, but you have your row/column matrixes covering SLK and MISO [B1 and B3]. Does the MDBT40 not actually need these pins? 

Also, it doesn't look like bluetooth is enabled in _rules.mk_, so I'm a little confused how the BT functionality works.

**Comment by scottywei** [comment]
Hi, I think you can find the code here: [#9602](https://github.com/qmk/qmk_firmware/pull/9602)

**Comment by latincompass** [comment]
> Hi!
> 
> I was looking at your QMK firmware for the G60BLE over https://github.com/qmk/qmk_firmware/blob/master/keyboards/bioi/g60ble/config.h and I'm a bit confused. Looks like you are using the MDBT40 chip, which normally hooks into _MISO/MOSI/SLK_, but you have your row/column matrixes covering SLK and MISO [B1 and B3]. Does the MDBT40 not actually need these pins?
> 
> Also, it doesn't look like bluetooth is enabled in _rules.mk_, so I'm a little confused how the BT functionality works.

Sir,The scottywei god use UART MOD,just vcc gnd TX RX,only 4 pins

**Comment by mrnoisytiger** [comment]
> Hi, I think you can find the code here: [#9602](https://github.com/qmk/qmk_firmware/pull/9602)

Thanks scottywei. You used UART which explains it. Thought you did SPI with QMK included BLE SPI. Thanks!
